# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-14 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='entry/%Y/%m/%d'),
        ),
    ]
