# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160204_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 2, 4, 3, 37, 25, 453708, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
