# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-18 03:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160514_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2016, 6, 18, 3, 36, 9, 571902, tzinfo=utc))),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='number_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='entrycomment',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.Entry'),
        ),
    ]
