# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160204_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='number_comments',
            field=models.IntegerField(default=0),
        ),
    ]
