# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-18 16:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160618_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 18, 16, 57, 12, 170617, tzinfo=utc)),
        ),
    ]
