# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-16 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160902_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycomment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
