# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160902_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=django_markdown.models.MarkdownField(),
        ),
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=django_markdown.models.MarkdownField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrycomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 20, 43, 34, 611266, tzinfo=utc)),
        ),
    ]
