# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-08 19:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160902_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 8, 19, 51, 31, 48499, tzinfo=utc)),
        ),
    ]
