# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-16 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20161005_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
