# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-07 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_entry_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrycomment',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
