# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-07 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_entrycomment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrycomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
