# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 23:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=False)),
                ('number_views', models.IntegerField(default=0)),
                ('number_comments', models.IntegerField(default=0)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('modified_date', models.DateTimeField()),
                ('publish_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actual_play/image/%Y/%m/%d')),
                ('audio_ogg', models.FileField(blank=True, null=True, upload_to='actual_play/audio/%Y/%m/%d/')),
                ('audio_mp3', models.FileField(blank=True, null=True, upload_to='actual_play/audio/%Y/%m/%d/')),
                ('video_ogv', models.FileField(blank=True, null=True, upload_to='actual_play/video/%Y/%m/%d/')),
                ('video_mp4', models.FileField(blank=True, null=True, upload_to='actual_play/video/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='GameComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='actual_play.Game')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('game_type', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('last_played', models.DateTimeField(verbose_name='last played')),
                ('status', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actual_play/player/%Y/%m/%d')),
                ('group', models.ManyToManyField(to='actual_play.GameGroup')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='actual_play.GameGroup'),
        ),
    ]
