# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='actual_play/audio/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='actual_play/video/%Y/%m/%d/'),
        ),
    ]
