# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-04 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actual_play_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
