# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
