# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-17 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0002_auto_20170609_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='audio_url',
            new_name='audio_url_mp3',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='video_url',
            new_name='audio_url_ogg',
        ),
        migrations.AddField(
            model_name='game',
            name='video_url_mp4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='video_url_ogv',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
