# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0002_auto_20160221_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actual_play/image/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actual_play/player/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='game',
            name='source_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
