# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-05 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0003_remove_gamecomment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamecomment',
            old_name='body',
            new_name='comment',
        ),
    ]
