# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-10 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0004_auto_20161005_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
