# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0005_auto_20160902_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 20, 43, 34, 618557, tzinfo=utc)),
        ),
    ]
