# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-06 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0006_auto_20160902_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecomment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 6, 22, 45, 28, 415055, tzinfo=utc)),
        ),
    ]
