# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-12-30 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0006_game_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
