# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-29 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0007_gamegroup_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(verbose_name='created date')),
                ('modified_date', models.DateTimeField(verbose_name='modified date')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('era', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='era', to='actual_play.GameEra')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='audio_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='game_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_type', to='actual_play.GameType'),
        ),
    ]
