# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-15 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0008_auto_20160914_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='audio',
            new_name='audio_mp4',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='video',
            new_name='video_mp4',
        ),
        migrations.AddField(
            model_name='game',
            name='audio_ogg',
            field=models.FileField(blank=True, null=True, upload_to='actual_play/audio/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='game',
            name='video_ogg',
            field=models.FileField(blank=True, null=True, upload_to='actual_play/video/%Y/%m/%d/'),
        ),
    ]
