# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-30 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0008_auto_20170529_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamecomment',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
