# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-15 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0009_auto_20160915_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='audio_mp4',
            new_name='audio_mp3',
        ),
    ]
