# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-23 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actual_play', '0011_game_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='video_ogg',
            new_name='video_ogv',
        ),
    ]
